// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WeeklyTask.Migrations.FoodDb
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20230215031920_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WeeklyTask.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/pizza.jpg",
                            Ingredients = "ham, pineapple, tomatoes",
                            Name = "Pizza",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/images/burger.jpg",
                            Ingredients = "beef, egg, cheese",
                            Name = "Hamburger",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/images/friedchicken.jpg",
                            Ingredients = "flour, egg, sauce",
                            Name = "Fried Chicken",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/images/spaghetti.jpg",
                            Ingredients = "tomatoes, sausage, cheese",
                            Name = "Spaghetti",
                            Price = 9.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
